import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { MainScreen } from "../src/components/main-screen";
import { Quiz } from "../src/components/quiz";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MyQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainScreen>
        <Quiz />
      </MainScreen>
    </>
  );
};

export default Home;
