import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useLayoutEffect, useMemo, useState } from "react";
import { MainScreen } from "../src/components/main-screen";
import { IDataProps, Quiz } from "../src/components/quiz";
import { Spinner } from "../src/components/spinner";
import { getData } from "../src/helpers/getData";

const randomArr = (arr: Array<string | any>) => {
  const cloneArr = [...arr];
  return Array(4)
    .fill("")
    .map(() => {
      const randomIndex = Math.floor(Math.random() * cloneArr.length);
      const [item] = cloneArr.splice(randomIndex, 1);

      return {
        name: item.name.common,
        flag: item.flags.png,
        capital: item.capital?.[0] || "any capital",
      };
    });
};

const themes = ["capital", "flag", "countryName"];

const Home: NextPage = () => {
  const [data, setData] = useState<IDataProps[]>([]);
  const [theme, setTheme] = useState("");
  const [isAnswered, setIsAnswered] = useState(false);

  const checkIsAnswered = () => {
    setIsAnswered((prev) => !prev);
  };

  useLayoutEffect(() => {
    getData()
      .then((res) => res.json())
      .then((result) => {
        const tempData: IDataProps[] = randomArr(result);
        setTimeout(() => setData(tempData), 300);
        return tempData;
      });
    setTheme(themes[Math.floor(Math.random() * themes.length)]);
  }, [isAnswered]);

  return (
    <>
      <Head>
        <title>MyQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainScreen>
        {data.length === 0 ? (
          <Spinner />
        ) : (
          <Quiz
            isAnswered={checkIsAnswered}
            rightAnswer={data[Math.floor(Math.random() * data.length)]}
            theme={theme}
            data={data}
          />
        )}
      </MainScreen>
    </>
  );
};

export default Home;
