import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import { MainScreen } from "../src/components/main-screen";
import { Quiz } from "../src/components/quiz";
import { Spinner } from "../src/components/spinner";
import { getData } from "../src/helpers/getData";

const randomArr = (arr: []) => {
  const cloneArr = [...arr];
  const newArr: never[] = [];
  for (let i = 0; i < 4; i++) {
    const randomIndex = Math.floor(Math.random() * cloneArr.length);
    newArr.push(cloneArr.splice(randomIndex, 1)[0]);
  }
  return newArr;
};

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    getData()
      .then((res) => res.json())
      .then((result) => {
        const tempData = randomArr(result);
        setData(tempData);
        console.log(randomArr(result));
      });
  }, []);
  return (
    <>
      <Head>
        <title>MyQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainScreen>{data.length === 0 ? <Spinner /> : <Quiz />}</MainScreen>
    </>
  );
};

export default Home;
